Repository depromeet/imgoing-frontend, pull requests merged in 2021-11, with the labels that each got.

#100 [Feature/kakao auth] 카카오 로그인 api 연동
  imgoing-frontend/.env.sample
  imgoing-frontend/src/components/Modal/DateWheelPickerModal.tsx
  imgoing-frontend/src/components/Modal/WebViewModal.tsx
  imgoing-frontend/src/components/Modal/index.tsx
  imgoing-frontend/src/environments.ts
  imgoing-frontend/src/modules/slices/modal.ts
  imgoing-frontend/src/modules/thunks/plan.ts
  imgoing-frontend/src/navigation/Navigator.tsx
  imgoing-frontend/src/screens/AuthLoadingScreen.tsx
  imgoing-frontend/src/screens/LoginScreen.tsx
  imgoing-frontend/src/types/Route.ts
  imgoing-frontend/src/types/env.d.ts
  imgoing-frontend/src/utils/request.ts
Labels: 공통, !important

#101 [Feature/kakao route api] 지도 확인 기능 구현
  imgoing-frontend/src/components/HomeMain/PlanItem.tsx
  imgoing-frontend/src/navigation/Navigator.tsx
  imgoing-frontend/src/screens/KakaoRouteScreen.tsx
  imgoing-frontend/src/types/Route.ts
Labels: 기능, Page|홈, major

#113 [Refactor/request] request 형태 변경
  imgoing-frontend/src/components/Modal/WebViewModal.tsx
  imgoing-frontend/src/modules/thunks/plan.ts
  imgoing-frontend/src/utils/request.ts
Labels: 공통, !important

#116 [Feature/bookmark api] 북마크 api 연동
  imgoing-frontend/src/components/BookmarkItem.tsx
  imgoing-frontend/src/components/HomeLanding/index.tsx
  imgoing-frontend/src/components/HomeMain/index.tsx
  imgoing-frontend/src/components/Modal/LoadBookmarkModal.tsx
  imgoing-frontend/src/modules/reducer.ts
  imgoing-frontend/src/modules/slices/bookmark.ts
  imgoing-frontend/src/modules/slices/plan.ts
  imgoing-frontend/src/modules/thunks/bookmark.ts
  imgoing-frontend/src/screens/AuthLoadingScreen.tsx
  imgoing-frontend/src/screens/PlanAddScreen.tsx
  imgoing-frontend/src/types/index.ts
Labels: 기능, 공통

#119 [Fix/PlanItem Text Error]: PlanItem에서 memo와 item이 없을때 비정상적으로 앱이 종료되는 문제
  imgoing-frontend/src/components/HomeMain/PlanItem.tsx
Labels: 버그, minor

#120 [Fix/PlanAdd Reset Error] Plan추가 후 편집시 상태가 지워지지 않는 오류 수정
  imgoing-frontend/src/screens/PlanAddScreen.tsx
Labels: 버그

#122 [Feature/toast] 공통 토스트 유틸 구현 및 적용
  imgoing-frontend/App.tsx
  imgoing-frontend/package.json
  imgoing-frontend/src/components/Modal/AddTaskModal.tsx
  imgoing-frontend/src/components/Modal/DeleteModal.tsx
  imgoing-frontend/src/components/Modal/MenuModal.tsx
  imgoing-frontend/src/components/Modal/TaskMenuModal.tsx
  imgoing-frontend/src/screens/PlanAddScreen.tsx
  imgoing-frontend/src/utils/toast.ts
  imgoing-frontend/yarn.lock
Labels: 기능, 공통

#121 [Feature/task order] 태스크 순서 변경 기능 추가
  imgoing-frontend/package.json
  imgoing-frontend/src/components/PlanAdd/UserInput.tsx
  imgoing-frontend/src/components/TaskItem.tsx
  imgoing-frontend/src/modules/slices/stepOfAddingPlan.ts
  imgoing-frontend/src/types/index.ts
  imgoing-frontend/yarn.lock
Labels: 기능, Page|등록하기, Page|편집하기

#124 [#117] fix: ScrollView의 아이템을 TouchableHightlight로 변경
  imgoing-frontend/package.json
  imgoing-frontend/yarn.lock
Labels: 버그

#127 [Feature/log out] 로그아웃 기능 구현
  imgoing-frontend/src/components/common/RoundButton.tsx
  imgoing-frontend/src/screens/SettingsScreen.tsx
Labels: 기능, 공통

#128 [Chore/deploy setting] 배포위한 이미지 변경 및 설정
  imgoing-frontend/app.json
  imgoing-frontend/assets/adaptive-icon.png
  imgoing-frontend/assets/favicon.png
  imgoing-frontend/assets/icon.png
  imgoing-frontend/assets/splash.png
Labels: 환경

#131 [Feature/modal component] 안드로이드에서 웹뷰 동작하지 않던 버그 수정
  imgoing-frontend/src/components/Modal/MenuModal.tsx
  imgoing-frontend/src/components/Modal/TaskMenuModal.tsx
  imgoing-frontend/src/components/Modal/index.tsx
  imgoing-frontend/src/layouts/RoundBottomModalLayout.tsx
Labels: 버그, 공통

#130 [Feature/PlanEditTaskMenuModal] PlanEditScreen에서 TaskMenuModal 연결
  imgoing-frontend/src/screens/PlanEditScreen.tsx
Labels: 기능, Page|편집하기

#135 [Feature/PlanEdit Task Drag] PlanEditScreen에 task 순서 변경 기능 추가
  imgoing-frontend/src/screens/PlanEditScreen.tsx
Labels: 기능

#136 [Feat/input limit] 긴 글 input 적용
  imgoing-frontend/src/components/PlanAdd/UserInput.tsx
  imgoing-frontend/src/components/PlanEdit/EditInputList.tsx
  imgoing-frontend/src/components/common/Input.tsx
Labels: 공통, minor

#143 [#139] fix : 엔터입력시 개행되지않도록 수정
  imgoing-frontend/src/components/common/Input.tsx
Labels: 기능, minor, 1.0

#140 [Bug/modal type] 삭제하기 모달 아래에 붙어있던 버그 수정
  imgoing-frontend/src/components/Modal/MenuModal.tsx
  imgoing-frontend/src/components/Modal/index.tsx
  imgoing-frontend/src/layouts/RoundBottomModalLayout.tsx
  imgoing-frontend/src/modules/slices/modal.ts
Labels: 버그, 공통

#137 [Feature/AuthLoadingSplash] 데이터가 로드되는 동안 splash페이지가 보이게 변경
  imgoing-frontend/App.tsx
  imgoing-frontend/package.json
  imgoing-frontend/src/modules/slices/plan.ts
  imgoing-frontend/src/modules/thunks/plan.ts
  imgoing-frontend/src/navigation/Navigator.tsx
  imgoing-frontend/src/screens/AuthLoadingScreen.tsx
  imgoing-frontend/src/screens/HomeScreen.tsx
  imgoing-frontend/src/screens/PlanEditScreen.tsx
  imgoing-frontend/yarn.lock
Labels: 기능, 공통

#151 feat: 정보처리 약관 모달 추가
  imgoing-frontend/app.json
  imgoing-frontend/src/components/Modal/WebViewAgreement.tsx
  imgoing-frontend/src/components/Modal/WebViewPolicy.tsx
  imgoing-frontend/src/components/Modal/index.tsx
  imgoing-frontend/src/modules/slices/modal.ts
  imgoing-frontend/src/screens/LoginScreen.tsx
  imgoing-frontend/src/screens/PlanAddScreen.tsx
Labels: 1.0

#152 v1.0.1 release
  docs/privacy_policy.html
  docs/terms_of_use_agreement.html
  imgoing-frontend/app.json
  imgoing-frontend/src/components/Modal/WebViewAgreement.tsx
  imgoing-frontend/src/components/Modal/WebViewPolicy.tsx
  imgoing-frontend/src/components/Modal/index.tsx
  imgoing-frontend/src/modules/slices/modal.ts
  imgoing-frontend/src/screens/LoginScreen.tsx
  imgoing-frontend/src/screens/PlanAddScreen.tsx
Labels: 1.0

#157 [Feature/prod setting] 프로덕션을 위한 세팅
  imgoing-frontend/.env.sample
  imgoing-frontend/app.json
  imgoing-frontend/package.json
  imgoing-frontend/src/components/Modal/WebViewLoginModal.tsx
  imgoing-frontend/src/components/Modal/index.tsx
  imgoing-frontend/src/environments.ts
  imgoing-frontend/src/screens/AuthLoadingScreen.tsx
  imgoing-frontend/src/screens/HomeScreen.tsx
  imgoing-frontend/src/types/env.d.ts
Labels: 버그, 기능, !important, 1.0

#181 design-token 패키지 추가
  packages/app/package.json
  packages/design-token/package.json
  packages/design-token/src/colors/index.ts
  packages/design-token/src/fonts/index.ts
  packages/design-token/src/index.ts
  packages/ui/package.json
  yarn.lock
Labels: 스타일, 공통

#183 베이스 코드 작업
  .github/PULL_REQUEST_TEMPLATE.md
  package.json
  packages/app/.env.sample
  packages/app/.eslintrc.js
  packages/app/App.tsx
  packages/app/app.json
  packages/app/babel.config.js
  packages/app/package.json
  packages/app/src/assets/adaptive-icon.png
  packages/app/src/assets/favicon.png
  packages/app/src/assets/icon.png
  packages/app/src/assets/splash.png
  packages/app/src/constant/index.ts
  packages/app/src/contexts/.gitkeep
  packages/app/src/environments.ts
  packages/app/src/hooks/.gitkeep
  packages/app/src/layouts/.gitkeep
  packages/app/src/mocks/.gitkeep
  packages/app/src/modules/reducer.ts
  packages/app/src/modules/store.ts
  packages/app/src/navigation/MainNavigation.tsx
  packages/app/src/navigation/RootNavigation.tsx
  packages/app/src/navigation/index.ts
  packages/app/src/screens/AuthLoadingScreen.tsx
  packages/app/src/screens/HomeScreen.tsx
  packages/app/src/screens/LoginScreen.tsx
  packages/app/src/screens/MyPlanScreen.tsx
  packages/app/src/screens/PlanInputScreen.tsx
  packages/app/src/screens/SettingsScreen.tsx
  packages/app/src/screens/WebviewScreen.tsx
  packages/app/src/screens/index.ts
  packages/app/src/theme/Metrics.ts
  packages/app/src/types/Route.ts
  packages/app/src/types/env.d.ts
  packages/app/src/types/redux.d.ts
  packages/app/src/types/theme.d.ts
  packages/app/src/utils/index.ts
  packages/app/tsconfig.json
  yarn.lock
Labels: 환경

#185 [Common] 타이포 그라피 설정 및 Text 컴포넌트 구현
  packages/design-token/src/fonts/Metrics.ts
  packages/design-token/src/fonts/index.ts
  packages/ui/package.json
  packages/ui/src/components/Test.tsx
  packages/ui/src/components/Text.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 공통

#186 [Common] font 파일 추가
  packages/app/src/assets/fonts/AppleSDGothicNeoB00.ttf
  packages/app/src/assets/fonts/AppleSDGothicNeoR00.ttf
Labels: 환경

#171 스위치 컴포넌트 구현
  packages/ui/src/components/SwitchButton.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 스타일, 공통

#174 숫자뱃지, 툴팁 컴포넌트 구현
  packages/ui/src/components/NumberBadge.tsx
  packages/ui/src/components/Tooltip.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 스타일, 공통

#179 SectionList & ListContainer 컴포넌트 구현
  packages/ui/src/components/ListContainer.tsx
  packages/ui/src/components/Stack.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 스타일, 공통

#188 [Chore] Request base type 설정
  packages/app/src/types/index.ts
Labels: 환경

#167 Input 컴포넌트 구현
  packages/ui/src/components/Input.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 공통

#169 InputGroup 컴포넌트 구현
  packages/ui/src/components/InputGroup.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 공통

#170 Icons 패키지 추가
  packages/icons/package.json
  packages/icons/src/index.ts
Labels: 공통

#173 Alert 컴포넌트 구현
  packages/ui/src/components/Alert.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 공통

#176 TextBage 컴포넌트 구현
  packages/ui/src/components/TextBadge.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 공통

#178 Button 컴포넌트 구현
  packages/ui/src/components/Button.tsx
  packages/ui/src/components/index.ts
Labels: 기능, 공통

#190 설정 페이지 UI 구현
  packages/app/App.tsx
  packages/app/package.json
  packages/app/src/components/Profile.tsx
  packages/app/src/navigation/MainNavigation.tsx
  packages/app/src/navigation/RootNavigation.tsx
  packages/app/src/screens/HomeScreen.tsx
  packages/app/src/screens/LoginScreen.tsx
  packages/app/src/screens/MyPlanScreen.tsx
  packages/app/src/screens/SettingsScreen.tsx
  packages/app/src/screens/WebviewScreen.tsx
  packages/icons/src/index.ts
  packages/ui/package.json
  packages/ui/src/components/Divider.tsx
  packages/ui/src/components/ListContainer.tsx
  packages/ui/src/components/NumberBadge.tsx
  packages/ui/src/components/Stack.tsx
  packages/ui/src/components/Test.tsx
  packages/ui/src/components/TextBadge.tsx
  packages/ui/src/components/Tooltip.tsx
  packages/ui/src/components/index.ts
  yarn.lock
Labels: Page|약속/지난일정/루틴/설정, 스타일, major
