Repository depromeet/imgoing-frontend, pull requests merged in 2021-12, with the labels that each got.

#199 Plan 타입 수정 및 모달 패키지 추가
  package.json
  packages/app/src/mocks/plan.mock.ts
  packages/app/src/types/index.ts
  yarn.lock
Labels: 공통

#195 myplan screen UI 구현
  packages/app/src/components/myPlan/IconBadge.tsx
  packages/app/src/components/myPlan/PlanStatistics.tsx
  packages/app/src/components/settings/Profile.tsx
  packages/app/src/screens/MyPlanScreen.tsx
  packages/app/src/screens/SettingsScreen.tsx
  packages/icons/src/index.ts
  packages/ui/src/components/NumberBadge.tsx
  packages/ui/src/components/Stack.tsx
  packages/ui/src/components/TextBadge.tsx
Labels: Page|약속/지난일정/루틴/설정, major

#196 홈 화면 마크업
  packages/app/App.tsx
  packages/app/src/components/Home/Schedule/Header.tsx
  packages/app/src/components/Home/Schedule/Plan.tsx
  packages/app/src/components/Home/Schedule/PlanDetails.tsx
  packages/app/src/components/Home/Schedule/Task.tsx
  packages/app/src/components/Home/Schedule/index.tsx
  packages/app/src/components/Home/TopContents/Guide.tsx
  packages/app/src/components/Home/TopContents/Task.tsx
  packages/app/src/components/Home/TopContents/TaskProcess.tsx
  packages/app/src/components/Home/TopContents/TimeRemaining.tsx
  packages/app/src/components/Home/TopContents/index.tsx
  packages/app/src/components/Home/type.tsx
  packages/app/src/components/myPlan/PlanStatistics.tsx
  packages/app/src/screens/HomeScreen.tsx
  packages/app/src/screens/LoginScreen.tsx
  packages/app/src/screens/WebviewScreen.tsx
  packages/icons/src/index.ts
  packages/ui/src/components/SvgIcon.tsx
  packages/ui/src/components/TextBadge.tsx
  packages/ui/src/components/index.ts
Labels: Page|홈, 스타일

#203 슬라이드 모달 레이아웃 구현
  package.json
  packages/app/package.json
  packages/design-token/src/fonts/index.ts
  packages/design-token/src/fonts/typo.ts
  packages/ui/package.json
  packages/ui/src/components/Modal/SlideUpModal.tsx
  packages/ui/src/components/Modal/index.ts
  packages/ui/src/components/index.ts
  yarn.lock
Labels: 기능, 공통
