Repository depromeet/imgoing-frontend, pull requests merged in 2021-10, with the labels that each got.

#10 [Feature/common-componets] 공통 컴포넌트 작성
  imgoing-frontend/src/components/common/Button.tsx
  imgoing-frontend/src/components/common/Input.tsx
  imgoing-frontend/src/components/common/RoundButton.tsx
  imgoing-frontend/src/components/typography/BodyTypo.tsx
  imgoing-frontend/src/components/typography/CalloutTypo.tsx
  imgoing-frontend/src/components/typography/CaptionTypo.tsx
  imgoing-frontend/src/components/typography/FootnoteTypo.tsx
  imgoing-frontend/src/components/typography/HeadlineTypo.tsx
  imgoing-frontend/src/components/typography/LargeTitleTypo.tsx
  imgoing-frontend/src/components/typography/SubheadlineTypo.tsx
  imgoing-frontend/src/components/typography/TitleTypo.tsx
  imgoing-frontend/src/types/index.ts
Labels: 기능

#17 [Chore/mock data] mock 데이터 생성
  imgoing-frontend/src/mock/plan.mock.ts
  imgoing-frontend/src/types/index.ts
Labels: 기능

#14 [Feature/home landing component] 홈랜딩 컴포넌트 구현
  imgoing-frontend/assets/images/close_button.png
  imgoing-frontend/assets/images/landing.png
  imgoing-frontend/src/components/HomeLanding/HomeLanding.tsx
  imgoing-frontend/src/components/HomeLanding/NotificationBar.tsx
  imgoing-frontend/src/components/common/RoundButton.tsx
  imgoing-frontend/src/components/typography/BaseTypo/index.tsx
  imgoing-frontend/src/constants/index.ts
  imgoing-frontend/src/screens/MainScreen.tsx
Labels: 기능, Page|홈, 스타일

#29 [Feature/icon svg component] 아이콘 svg로 추가
  imgoing-frontend/assets/svg/index.ts
  imgoing-frontend/assets/svg/kakaoMap.ts
  imgoing-frontend/package.json
  imgoing-frontend/src/navigation/BottomTabNavigator.tsx
  imgoing-frontend/yarn.lock
Labels: 스타일

#20 [Feature/home main component] HomeMain 컴포넌트 구현 및 Typo 오류뜨는 부분 수정 반영
  imgoing-frontend/assets/images/down.png
  imgoing-frontend/assets/images/kakaomap.png
  imgoing-frontend/assets/images/menu.png
  imgoing-frontend/assets/images/pin.png
  imgoing-frontend/assets/images/plus.png
  imgoing-frontend/assets/images/up.png
  imgoing-frontend/assets/images/⏳.png
  imgoing-frontend/assets/images/✏️.png
  imgoing-frontend/assets/images/🎒️.png
  imgoing-frontend/assets/images/📍.png
  imgoing-frontend/src/components/HomeLanding/HomeLanding.tsx
  imgoing-frontend/src/components/HomeLanding/NotificationBar.tsx
  imgoing-frontend/src/components/HomeMain/DeleteModal.tsx
  imgoing-frontend/src/components/HomeMain/HomeMain.tsx
  imgoing-frontend/src/components/HomeMain/IconButton.tsx
  imgoing-frontend/src/components/HomeMain/MenuModal.tsx
  imgoing-frontend/src/components/HomeMain/PlanItem.tsx
  imgoing-frontend/src/components/HomeMain/PlanList.tsx
  imgoing-frontend/src/components/HomeMain/TimeReminder.tsx
  imgoing-frontend/src/screens/MainScreen.tsx
Labels: 기능, Page|홈, 스타일

#30 [Feature/icon svg component] svg 아이콘 백그라운드 수정
  imgoing-frontend/assets/svg/index.ts
  imgoing-frontend/assets/svg/landingCharacter.ts
  imgoing-frontend/src/navigation/BottomTabNavigator.tsx
Labels: 스타일

#43 [Feature/modal component] modal 공통 component 구현 및 리듀서 설정
  imgoing-frontend/App.tsx
  imgoing-frontend/src/components/HomeMain/DeleteModal.tsx
  imgoing-frontend/src/components/HomeMain/PlanItem.tsx
  imgoing-frontend/src/components/Modal/DeleteModal.tsx
  imgoing-frontend/src/components/Modal/MenuModal.tsx
  imgoing-frontend/src/components/Modal/index.tsx
  imgoing-frontend/src/modules/reducer.ts
  imgoing-frontend/src/modules/slices/modal.ts
  imgoing-frontend/src/modules/store.ts
  imgoing-frontend/src/navigation/MainBottomTab.tsx
  imgoing-frontend/src/screens/PlanEditScreen.tsx
  imgoing-frontend/src/types/redux.d.ts
Labels: 기능, 환경

#46 [Fix/modal component] MenuModal 및 DeleteModal 컴포넌트 수정
  imgoing-frontend/src/components/HomeMain/PlanItem.tsx
  imgoing-frontend/src/components/Modal/DeleteModal.tsx
  imgoing-frontend/src/components/Modal/MenuModal.tsx
Labels: 버그

#91 feat: PlanEdit에서 redux연결이 되어있지 않았던 부분 연결
  imgoing-frontend/src/components/PlanEdit/EditInputList.tsx
  imgoing-frontend/src/components/TaskItem.tsx
  imgoing-frontend/src/modules/slices/stepOfAddingPlan.ts
  imgoing-frontend/src/screens/PlanEditScreen.tsx
Labels: Page|편집하기
