Repository depromeet/imgoing-frontend, pull requests merged in 2022-02, with the labels that each got.

#217 탭바 아이콘 추가
  packages/app/src/navigation/MainNavigation.tsx
  packages/icons/src/index.ts
Labels: 기능, 공통

#214 홈 화면 최상단 컴포넌트 시간 계산
  package.json
  packages/app/package.json
  packages/app/src/components/Home/Schedule/PlanDetails.tsx
  packages/app/src/components/Home/Schedule/index.tsx
  packages/app/src/components/Home/TopContents/RemainingTime.tsx
  packages/app/src/components/Home/TopContents/Task.tsx
  packages/app/src/components/Home/TopContents/TaskProcess.tsx
  packages/app/src/components/Home/TopContents/index.tsx
  packages/app/src/components/Home/TopContents/utils/index.ts
  packages/app/src/components/Home/type.tsx
  packages/app/src/modules/services/plan.ts
  packages/app/src/screens/HomeScreen.tsx
  packages/app/src/types/index.ts
  packages/app/src/utils/date.ts
  packages/app/src/utils/index.ts
  yarn.lock
Labels: 기능, Page|홈

#218 Feat/routine modal
  packages/app/src/components/MyPlan/PastPlan/PastPlanItem.tsx
  packages/app/src/components/MyPlan/PastPlan/type.ts
  packages/app/src/components/MyPlan/Routine/AddingTaskModal.tsx
  packages/app/src/components/MyPlan/Routine/HistoryModal.tsx
  packages/app/src/components/MyPlan/Routine/LandingView.tsx
  packages/app/src/components/MyPlan/Routine/RoutineItem.tsx
  packages/app/src/components/MyPlan/Routine/RoutineList.tsx
  packages/app/src/components/MyPlan/Routine/TaskItem.tsx
  packages/app/src/components/MyPlan/Routine/type.ts
  packages/app/src/screens/RoutineEditScreen.tsx
  packages/icons/src/index.ts
  packages/ui/package.json
  packages/ui/src/components/Modal/SlideUpModal.tsx
  packages/ui/src/components/WheelPicker.tsx
  packages/ui/src/components/index.ts
  yarn.lock
Labels: 기능, major

#219 패키지 설치 오류 관련
  packages/ui/package.json
  yarn.lock
Labels: 버그
